insert into geek values (1, 'melie46285', 'Amelie', 'Poyet',  'a.poyet@geektic.com', 0);
insert into geek values (2, 'judur', 'Justine', 'Durand', 'j.durand@geektic.com', 0);
insert into geek values (3, 'johnny', 'John', 'Maillot', 'j.maillot@geektic.com', 1);
insert into geek values (4, 'mister ced', 'Cedric', 'Vairon', 'c.vairon@geektic.com', 1);
insert into geek values (5, 'MM', 'Marie', 'Mouterde', 'm.mouterde@geektic.com', 0);
insert into geek values (6, 'billy', 'Bill', 'Boquet', 'b.boquet@geektic.com', 1);
insert into geek values (7, 'scholf', 'wolfgang', 'Schopenhauer', 'w.schopenhauer@geektic.com', 1);
insert into geek values (8, 'wesh_j_ai_un_rap_de_ouf_pete_sa_race', 'Mohammed', 'Aïdin', 'wesh.meme.mon.mail.cest.trop.de.la.balle@geektic.com', 1);
insert into geek values (9, 'mambo_number5', 'Lou', 'Béga', 'l.bega@geektic.com', 0);
insert into geek values (10, 'triiieur', 'Michel', 'Jactionne', 'm.jactionne@geektic.com', 1);
insert into geek values (11, 'hylien', 'Link', 'Jaipasdenom', 'l.jaipasdenom@geektic.com', 1);
insert into geek values (12, 'hylienne', 'Zelda', 'Moinonplus', 'z.moinonplus@geektic.com', 0);
insert into geek values (13, 'chosen1', 'Neo', 'Anderchouine', 'n.anderchouine@geektic.com', 1);
insert into geek values (14, 'chosen2', 'Trinity', 'Etobago', 't.etobago@geektic.com', 0);
insert into geek values (15, 'Oh_Yeah', 'Duff', 'Man', 'd.man@geektic.com', 1);
insert into geek values (16, 'la_drogue_cest_mal_je_vais_vous_la_prendre', 'Hulk', 'Arbeson', 'h.arbeson@geektic.com', 1);

insert into interet values ('C');
insert into interet values ('C++');
insert into interet values ('C#');
insert into interet values ('Java');
insert into interet values ('PHP');
insert into interet values ('TDD');
insert into interet values ('JUnit');
insert into interet values ('Javascript');
insert into interet values ('Unix');
insert into interet values ('Assembleur');
insert into interet values ('Perl');
insert into interet values ('Android');

insert into geekInteret values (1, 'Android');
insert into geekInteret values (1, 'C');
insert into geekInteret values (2, 'C++');
insert into geekInteret values (2, 'Perl');
insert into geekInteret values (3, 'Android');
insert into geekInteret values (4, 'Unix');
insert into geekInteret values (4, 'Assembleur');
insert into geekInteret values (5, 'Java');
insert into geekInteret values (6, 'Java');
insert into geekInteret values (7, 'C');
insert into geekInteret values (7, 'C++');
insert into geekInteret values (7, 'C#');
insert into geekInteret values (8, 'Javascript');
insert into geekInteret values (8, 'Assembleur');
insert into geekInteret values (9, 'Perl');
insert into geekInteret values (10, 'TDD');
insert into geekInteret values (10, 'PHP');
insert into geekInteret values (11, 'JUnit');
insert into geekInteret values (12, 'JUnit');
insert into geekInteret values (13, 'PHP');
insert into geekInteret values (14, 'Android');
insert into geekInteret values (14, 'C');
insert into geekInteret values (15, 'Assembleur');
insert into geekInteret values (16, 'C');
insert into geekInteret values (16, 'C++');
insert into geekInteret values (16, 'C#');
insert into geekInteret values (16, 'Java');
insert into geekInteret values (16, 'PHP');
insert into geekInteret values (16, 'TDD');
insert into geekInteret values (16, 'JUnit');
insert into geekInteret values (16, 'Javascript');
insert into geekInteret values (16, 'Unix');
insert into geekInteret values (16, 'Assembleur');
insert into geekInteret values (16, 'Perl');
insert into geekInteret values (16, 'Android');